
export enum OFFER_BULK_UPLOAD_ACTION_TYPE {
    // OFFER_BULK_UPLOAD_ACTION_TYPE
    BULK_UPLOAD_OFFER = '[BULK OFFER UPLOAD] Bulk Upload',
    BULK_UPLOAD_OFFER_SUCCESS = '[BULK OFFER UPLOAD] Bulk Upload Success',
    BULK_UPLOAD_OFFER_FAILURE = '[BULK OFFER UPLOAD] Bulk Upload Failure',
    REMOVE_OFFER_BY_OFFER_ID = '[BULK OFFER UPLOAD] Remove Offer By Offer Id',
    CLEAR_UPLOADED_OFFERS = '[BULK OFFER UPLOAD] Clear Uploaded Offers',
    PUBLISH_OFFERS = '[BULK OFFER UPLOAD] Publish Offers',
    PUBLISH_OFFERS_SUCCESS = '[BULK OFFER UPLOAD] Publish Offers Success',
    PUBLISH_OFFERS_FAILURE = '[BULK OFFER UPLOAD] Publish Offers Failure',
}
