export enum CREATE_OFFER_ACTION_TYPE {
    CREATE_OFFER_IMAGE_UPLOAD = '[CreateOffer] Create Offer Image Upload',
    CREATE_OFFER_VIDEO_UPLOAD = '[CreateOffer] Create Offer Video Upload',
    CREATE_OFFER_DOC_UPLOAD = '[CreateOffer] Create Offer Document Upload',
    CREATE_DRAFT_OFFER_DOC_UPLOAD = '[CreateOffer] Create Draft Offer Document Upload',
    CREATE_DRAFT_OFFER_MEDIA = '[CreateOffer] Create Draft Offer Media Upload',
    UPDATE_PUBLISHED_OFFER_MEDIA = '[CreateOffer] Update Published Offer Media',
    CREATE_DRAFT_OFFER_IMAGE_UPLOAD = '[CreateOffer] Create Draft Offer Image Upload',
    CREATE_DRAFT_OFFER_VIDEO_UPLOAD = '[CreateOffer] Create Draft Offer Video Upload',

    CREATE_OFFER_MEDIA_UPLOAD_SUCCESS = '[CreateOffer] Create Offer Media Upload Success',
    CREATE_OFFER_MEDIA_UPDATE_SUCCESS = '[CreateOffer] Create Offer Media Update Success',
    CREATE_OFFER_MEDIA_UPLOAD_PROGRESS = '[CreateOffer] Create Offer Media Upload Progress',
    CREATE_OFFER_UPLOAD_PROGRESS = '[CreateOffer] Create Offer Media Upload Progress',
    CREATE_OFFER_MEDIA_UPLOAD_FAILURE = '[CreateOffer] Create Offer Media Upload Failure',
    CREATE_OFFER_MEDIA_DELETE_FAILURE = '[CreateOffer] Create Offer Media Delete Failure',
    CREATE_OFFER_SUGGESTED_CATEGORY = '[CreateOffer] Create Offer Suggested Category',
    CREATE_OFFER_SUGGESTED_CATEGORY_SUCCESS = '[CreateOffer] Create Offer Suggested Category Success',

    DRAFT_OFFER_IMAGE_UPLOAD_SUCCESS = '[CreateOffer] Draft Offer Image Upload Success',
    DRAFT_OFFER_IMAGE_UPLOAD_PROGRESS = '[CreateOffer] Draft Offer Image Upload Progress',
    DRAFT_OFFER_IMAGE_UPLOAD_FAILURE = '[CreateOffer] Draft Offer Image Upload Failure',

    DRAFT_OFFER_VIDEO_UPLOAD_SUCCESS = '[CreateOffer] Draft Offer Video Upload Success',
    DRAFT_OFFER_VIDEO_UPLOAD_PROGRESS = '[CreateOffer] Draft Offer Video Upload Progress',
    DRAFT_OFFER_VIDEO_UPLOAD_FAILURE = '[CreateOffer] Draft Offer Video Upload Failure',

    CREATE_OFFER_REMOVE_MEDIA = '[CreateOffer] Create Offer Remove Media',
    CREATE_OFFER_REMOVE_DRAFT_MEDIA = '[CreateOffer] Create Offer Draft Remove Media',
    CREATE_OFFER_REMOVE_PUBLISHED_MEDIA = '[CreateOffer] Create Offer Published Remove Media',
    CREATE_OFFER_REMOVE_MEDIA_SUCCESS = '[CreateOffer] Create Offer Remove Media Success',
    CREATE_OFFER_REMOVE_MEDIA_FAILURE = '[CreateOffer] Create Offer Remove Media Failure',
    CREATE_OFFER_REMOVE_VIDEO = '[CreateOffer] Create Offer Remove Video',
    CREATE_OFFER_REMOVE_VIDEO_SUCCESS = '[CreateOffer] Create Offer Remove Video Success',
    CREATE_OFFER_REMOVE_VIDEO_FAILURE = '[CreateOffer] Create Offer Remove Video Failure',

    CREATE_OFFER_SET_COVER_MEDIA = '[CreateOffer] Create Offer Set Cover Media',

    ADD_CREATE_OFFER_INFO = '[CreateOffer] Add Create Offer Info',
    UPDATE_CREATE_OFFER_LOCATION = '[CreateOffer] Update Create Offer Location',
    CREATE_OFFER_NAVIGATE_SCREEN = '[CreateOffer] Create Offer navigate screen',
    SUBMIT_OFFER = '[CreateOffer] Create Offer submit offer',
    UPDATE_OFFER = '[CreateOffer] Create Offer update offer',
    PUT_OFFER = '[CreateOffer] Create Offer update offer',
    SUBMIT_OFFER_SUCCESS = '[CreateOffer] Create Offer submit offer success',
    SUBMIT_OFFER_FAILURE = '[CreateOffer] Create Offer submit offer faileds',

    ADDRESS_FETCH = '[CreateOffer] Fetch User Address',
    ADDRESS_DATA_SUCCESS = '[CreateOffer] Fetch User Address Success',
    ADDRESS_DATA_FAILURE = '[CreateOffer] Fetch User Address Failure',
    ADD_USER_ADDRESS = '[CreateOffer] Add User Address',
    ADD_USER_ADDRESS_SUCCESS = '[CreateOffer] Add User Address Success',
    ADD_USER_ADDRESS_FAILURE = '[CreateOffer] Add User Address Failure',
    RESET_ADDRESS_STATE = '[CreateOffer] Offer Address reset',
    UPDATE_USER_LOCATION = '[CreateOffer] Update User Location',
    UPDATE_USER_ADDRESS = '[CreateOffer] Update User Address',
    CLEAR_OFFER_DATA = '[CreateOffer] Clear Offer Data',

    FETCH_OFFER_INITIAL_DATA = '[CreateOffer] Fetch Offer Initial Data',
    FETCH_OFFER_INITIAL_DATA_SUCCESS = '[CreateOffer] Fetch Offer Initial Data Success',
    FETCH_OFFER_INITIAL_DATA_FAILURE = '[CreateOffer] Fetch Offer Initial Data Failure',

    // categories 

    ADD_SELECTED_TAGS_BY_CATEGORIES = '[CreateOffer] Add Tag By Selected Category',
    ADD_SELECTED_TAGS_BY_CATEGORIES_SUCCESS = '[CreateOffer] Add Tag By Selected Category Success',
    GET_SELECTED_TAGS_BY_USER_INFO = '[CreateOffer] Get Selected Tag By User Info',
    GET_SELECTED_TAGS_BY_USER_INFO_SUCCESS = '[CreateOffer] Get Selected Tag By User Info Success',
    ADD_SELECTED_DESIRE_CATEGORIES = '[CreateOffer] Add Selected Desire Category',
    REMOVE_SELECTED_CATEGORIES = '[CreateOffer] Remove Selected Category',
    REMOVE_SELECTED_DESIRE_CATEGORIES = '[CreateOffer] Remove Selected Desire Category',
    CREATE_DRAFT_OFFER = '[CreateOffer] Create Draft Offer',
    UPDATE_DRAFT_OFFER = '[CreateOffer] Update Draft Offer',
    UPDATE_DRAFT_OFFER_SINGLE = '[CreateOffer] Update Draft Offer Single',
    UPDATE_DRAFT_OFFER_LOCAL = '[CreateOffer] Update Draft Offer Local',
    UPDATE_DRAFT_OFFER_LOCAL_SERVICE_TIMING = '[CreateOffer] Update Draft Offer Local Service Timing',
    UPDATE_DRAFT_SERVICE_LOCATION_OFFER_LOCAL = '[CreateOffer] Update Draft Service Location Offer Local',
    STORE_VERTICAL_CATEGORIES_FAILURE = '[CreateOffer] Store vertical category failure',
    SET_TAGS_SELECTED_CATEGORY = '[CreateOffer] Set Tags of Selected category',
    SET_SELECTED_FACETS = '[CreateOffer] Set Selected Facets',
    CLEAR_FACETS = '[CreateOffer] Clear Selected Facets',

    // draft
    FETCH_OFFER_DRAFT_DATA = '[CreateOffer] Fetch Offer Draft Data',
    FETCH_OFFER_PUBLISHED_DATA = '[CreateOffer] Fetch Offer Published Data',
    CREATE_CLONE_DRAFT_OFFER = '[CreateOffer] Create Clone Draft Offer',
    OFFER_DRAFT_DATA_SUCCESS = '[CreateOffer] Offer Draft Data success',
    OFFER_CATEGORY_DATA_SUCCESS = '[CreateOffer] Offer Category Data success',
    OFFER_FACET_DATA_SUCCESS = '[CreateOffer] Offer Facet Data success',
    OFFER_DESIRE_DATA_SUCCESS = '[CreateOffer] Offer Desire Data success',
    OFFER_DRAFT_DATA_FAILURE = '[CreateOffer] Offer Draft Data failure',
    REMOVE_DRAFT_OFFER = '[CreateOffer] Remove Offer Draft Data',
    REMOVE_DRAFT_OFFER_SUCCESS = '[CreateOffer] Remove Offer Draft Data Success',
    // offer posting loader
    CREATE_OFFER_POSTING_LOADER = '[Create] offer posting loader',

    // enable offer sections
    ENABLE_ACCORDION_ONE = '[CreateOffer] Enable Accordion One',
    ENABLE_ACCORDION_TWO = '[CreateOffer] Enable Accordion Two',
    DISABLE_ACCORDION_TWO = '[CreateOffer] Disable Accordion Two',
    ENABLE_ACCORDION_THREE = '[CreateOffer] Enable Accordion Three',
    DISABLE_ACCORDION_THREE = '[CreateOffer] Disable Accordion Three',
    ENABLE_POST_OFFER_SECTION = '[CreateOffer] Enable Post Offer Section',
    DISABLE_POST_OFFER_SECTION = '[CreateOffer] Disable Post Offer Section',
    DISABLE_ACCORDION_ONE = '[CreateOffer] Disable Accordion One',
    RESET_SECTION_TOGGLES = '[CreateOffer] Reset Section Toggles',
    ENABLE_DOCUMENTS_SECTION = '[CreateOffer] Enable Documents Section',
    DISABLE_DOCUMENTS_SECTION = '[CreateOffer] Disable Documents Section',
    DISABLE_OFFER_TAB = '[CreateOffer] Disable Offer Tab',
    ENABLE_OFFER_TAB = '[CreateOffer] Enable Offer Tab',
    RESET_OFFER_TABS = '[CreateOffer] Reset Offer Tabs',
    UPDATE_CURRENT_ACTIVE_SECTION = '[CreateOffer] Update Current Active Section',
    MEDIA_UPLOAD_START = '[CreateOffer] Media Upload Start',
    MEDIA_UPLOAD_COMPLETE = '[CreateOffer] Media Upload Complete',
    UNSET_OFFER_POST_FAILURE = '[CreateOffer] Unset Offer Post Failure',
    UNSET_IMAGE_UPLOAD_FAILED = '[CreateOffer] Unset Image Upload Failed',
    FETCH_BUSINESS_DETAILS = '[CreateOffer] Fetch Business Details',
    FETCH_BUSINESS_DETAILS_SUCCESS  = '[CreateOffer] Fetch Business Details Success',
    FETCH_BUSINESS_DETAILS_FAILURE  = '[CreateOffer] Fetch Business Details Failure',
    UPDATE_LOCATION_TITLE = '[CreateOffer] Update Business Location Title',
    ADD_BUSINESS_ADDRESS = '[CreateOffer] Add Business Address',
    ADD_BUSINESS_ADDRESS_SUCCESS = '[CreateOffer] Add Business Address Success',
    ADD_BUSINESS_ADDRESS_FAILURE = '[CreateOffer] Add Business Address Failure',
}
