const localization = {
    user: {
        USER_ADDRESS_ADD_SUCCESS: 'Profile Address Added Successfully',
        USER_ADDRESS_EDIT_SUCCESS: 'Profile Address Updated Successfully',
        USER_IMAGE_UPLOAD_SUCCESS: 'Profile Image Upload Successfully',
        USER_IMAGE_UPLOAD_ERROR: 'Profile Image Upload Failed',
        USER_EMAIL_VERIFIED_SUCCESS: 'Successfully verified email',
        USER_MOBILE_VERIFIED_SUCCESS: 'Successfully verified phone',
        FAILED_TRY_AGAIN: 'Filed! Please try again',
        USER_PROFILE_UPDATED: 'User profile updated successfully',
        OTP_SENT_ON: 'OTP has been send on',
        VERIFICATION_FAILED_INVALID_OTP: 'Verification failed! Invalid OTP',
        DEFAULT_ADDRESS_FAILED: 'Failed to save default address',
        REMOVE_PROFILE_IMAGE_FAILED: 'Failed to remove profile image',
        REMOVE_PROFILE_IMAGE_SUCCESS: 'Profile image removed Successfully',
        REPORT_OTHER_USER: 'You reported the user successfully.',
        REPORT_AND_BLOCK_USER: 'You reported & blocked the user successfully.',
        BLOCK_USER: 'You blocked the user successfully.',
        REPORT_USER_ERR: 'Error occurred! Please try again.'
    },
    deal: {
        USER_ADDRESS_ADD_SUCCESS: 'Profile Address Added Successfully',
        VERIFICATION_FAILED_INVALID_OTP: 'Verification failed! Invalid OTP',
        OTP_GENERATE_FAILED: 'Failed to generate OTP, please try after some time',
        OTP_GENERATE_SUCCESS: 'Otp sent success',
        REJECTED_SUCCESS: 'Offer rejected success!',
        SUGGEST_DEAL_SUCCESS: 'Offer Initate Successful!',
        NO_DEAL_FOUND: 'No Offer Available',
        DEAL_ACCEPT_FAILED: 'Offer accept failed. Please try again.',
        DEAL_REJECT_FAILED: 'Offer rejection failed. Please try again.',
        DEAL_REJECT_SUCCESS: 'Offer rejected succesfully!',
        DEAL_RATING_FAILED: 'Failed to post rating, please try after some time',
        SUGGEST_DEAL_FAILED: 'Failed to suggest offer, please try again!',
        REVISE_DEAL_FAILED: 'Failed to make counter offer, offer please try again!',
        OFFER_NOT_FOUND: 'Offer Id not found.',
        HISTORY_FAILED: 'Offer history not found',
        ADD_DEAL_FAVOURITE_SUCCESS: 'Offer Favourite added successfully!',
        ADD_DEAL_FAVOURITE_FAILED: 'Failed to  add Favourite Offer!',
        REMOVE_DEAL_FAVOURITE_SUCCESS: 'Offer Favourite removed successfully!',
        REMOVE_DEAL_FAVOURITE_FAILED: 'Failed to remove Favourite Offer!',
        PAYMENT_FAILED: 'Failed to initate payment, Please try again!',
        ACCOUNT_DETAILS_REQUIRED: 'Please Update Account details',
    },
    offer: {
        ADD_OFFER_FAVORITES: 'Offer added into favourite successfully!',
        REMOVE_OFFER_FAVORITES: 'Offer removed from favourite successfully!',
        ADD_OFFER_FAVORITES_FAILURE: 'failed to add offer into favorites!',
        OFFER_REPORTED_SUCCESS: 'Offer reported successfully!',
        POST_OFFER_FAILURE: 'Failed to post offer',
        MEDIA_UPLOAD_FAILURE: 'Failed to upload media',
    },
    business: {
        INVITATION_ACCEPTED: 'Invitation accepted',
        INVITATION_REJECTED: 'Invitation rejected',
    },
    others: {
        INVALID_OPERATION: 'Invalid Operation',
        AUTH_FAILED: 'Authentication Failed',
    },
    
}
export default localization;