export enum NotiFicationTypes {
    // NewDealSuggestion = "NewDealSuggestion",
    // OfferApproved = "OfferApproved",
    // OfferCreated = "OfferCreated",
    // NewMatch = "NewMatch",
    // SuccessDealClose = "SuccessDealClose",
    // DealAcceptance = "DealAcceptance",
    // OfferBidReceived="OfferBidReceived",

    offerPublished = 'offer_published',
    offerUnserReview = "offer_under_review",
    offerEdited = "offer_edited",
    offerDeleted = "offer_deleted",
    autionOfTheDay = "auctions_of_the_day",
    autctionExpired = "auction_expired",
    auctionClosed = "auction_closed",
    auctionOwned = "auction_owned",
    dealSuggested = "deal_suggested",
    newMatch = "new_match",
    newBids = "new_bids",
    dealAccpted = "deal_accepted",
    dealRejected = "deal_rejected",
    dealRevised = "deal_revised",
    dealClosed = "deal_closed",
}